### ISSUE TITLE
Ubuntu error

### ISSUE THREAD

**Issue by jasondreher** [scadagenius/obisyslog#2]
I fill in all the info in the config.yaml and run python3 main_obihai.py but get the error below, any idea what i need t change? i am running in Ubuntu.

Config folder: /config/
Traceback (most recent call last):
  File "main_obihai.py", line 34, in <module>
    main_object = ObihaiMonitor(root_path)
  File "main_obihai.py", line 10, in __init__
    self.helper = ObihaiHelper(config_folder)
  File "/home/jason/Scripts/obisyslog/obihai_helper.py", line 21, in __init__
    self.config = yaml.load(open(self.config_folder + 'config.yaml'))
FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yaml'

**Comment by scadagenius** [comment]
I think you missed dot (.) in the command at the end as documented in the readme file.
Please try as shown below and notice a space and dot at the end, that tells config file is in the current folder:

`python3 main_obihai.py .
`

Please report back so I can close the issue.
Thanks.

**Comment by jasondreher** [comment]
that worked thanks!!!

**Comment by scadagenius** [comment]
Thanks! Enjoy!
